---
ID: "47f785b0-07e0-4ecc-a476-7264f4a2d581"
Parent: "35f72bc4-3b9e-4c4a-9309-dad3c025773b"
Template: "35f72bc4-3b9e-4c4a-9309-dad3c025773b"
Path: "/sitecore/templates/Project/collection-1/Services/Rendering Parameters/HeroBanner Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "34d2c5c0-fd2a-427d-9765-fd4980f960e3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250425T041256Z
