---
ID: "1db039a0-6550-4e0b-8c99-7a60007c616a"
Parent: "b32440e6-4124-4395-a1f4-8c9b76321694"
Template: "b32440e6-4124-4395-a1f4-8c9b76321694"
Path: "/sitecore/templates/Project/collection-1/Services/Rendering Parameters/ProductList Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "77fd8aec-2a39-460f-a9ce-5d64979a504d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250430T045941Z
