---
ID: "209b67ed-9134-4b89-8855-081a36a34bd8"
Parent: "b50ece7a-cdc5-42d8-9874-ffdd8fc0d8a6"
Template: "c3b037a0-46e5-4b67-ac7a-a144b962a56f"
Path: "/sitecore/layout/Placeholder Settings/Project/collection-1/Services"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T102306Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "deecaf97-186e-44ca-b412-07068df6e672"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250417T102306Z
