---
ID: "b2a42fb8-2fda-4df3-9827-63dcf85af7b8"
Parent: "da2b4a86-8cdc-48be-b783-4c32524bb173"
Template: "da2b4a86-8cdc-48be-b783-4c32524bb173"
Path: "/sitecore/templates/Project/collection-1/Services/Rendering Parameters/Services Teaser Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9a8e612b-41e1-471e-8b9f-a24f95a55a10"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250417T122925Z
