---
ID: "0c84cfb2-6e8c-41f0-8953-41cb9ebfe22a"
Parent: "36ba4f18-b449-418e-be04-6f571f92a3f0"
Template: "76da0a8d-fc7e-42b2-af1e-205b49e43f98"
Path: "/sitecore/content/collection-1/sample-site/Presentation/Available Renderings/Services"
BranchID: "678a1f11-e74b-4663-ae6b-6c8ec28c1c1d"
SharedFields:
- ID: "715ae6c0-71c8-4744-ab4f-65362d20ad65"
  Hint: Renderings
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b1e91e40-a15c-47ae-8554-05d3dfd90acf"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0B2EB1AC-1B6D-4D7E-95CB-E39C8B4E9A57}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T103941Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "399d6423-95e3-4ef6-8a89-ea0526a33235"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250417T121300Z
