---
ID: "3e5638c8-64bc-4aa5-8830-de04cf179062"
Parent: "0eb5adb7-86ab-482c-91f9-d57f0bdecab8"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: "/sitecore/templates/Project/collection-1/Services"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T122751Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e8d6fba9-d131-49ba-8931-4bf3d03924e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rutvik.pankhania@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250417T122751Z
