---
ID: "c7de28bf-b22a-4015-b0b7-26cad420ca31"
Parent: "9bd49be3-2c5f-43c1-9a59-88e48a0071aa"
Template: "9bd49be3-2c5f-43c1-9a59-88e48a0071aa"
Path: "/sitecore/templates/Project/collection-1/Headless Tenant/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250416T101923Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3180adb7-d73d-4a3a-a250-0003ee9b80cb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250416T101923Z
