---
ID: "8e895dcd-724e-410a-96cf-53d9f31398ba"
Parent: "00d31fc1-485a-44b7-acf5-a0d0f463e254"
Template: "c95e9939-43a0-4c23-a382-ccb292147477"
Path: "/sitecore/content/collection-1/sample-site/Home/Products"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{45F2A546-48DD-4288-AE16-78FC260FD39D}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c8914ace-a942-4863-87e2-66854fa8aae6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}"
              p:before="*"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7BE25B16F8-81E2-443F-B4B0-500E08F42815%7D&amp;FieldNames=%7B5B290361-359A-440F-B069-A6B572F050C8%7D&amp;Styles=%7C%7BED9F23D9-7CB6-46AB-8AED-1086E2E517F2%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{ECBD8335-1F9E-4FCC-80CE-0E4B85E2A298}"
              p:after="r[@uid='{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}']"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Text%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=p8-7UeJ8C0&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=fM94UIWfrYAUphV&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Text%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
              s:ph="headless-main" />
            <r
              uid="{93306911-25A3-4414-A134-C6DFF667C3D1}"
              p:after="*[1=2]"
              s:ds="50647fa5-c746-4fb6-ac01-e4016fa0d017"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Image%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=cqLZMpmZph&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=xz4P-c_gGUeJ3Iu&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Image%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T090143Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rachit.bansal@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rachit.bansal@valtech.com
    - ID: "6526ebe8-cb6e-4196-9f02-4406a7b939e8"
      Hint: Content
      Value: |
        <h1><span style="color: rgb(16, 56, 79);">With our products we contribute to the health of people, animals and plants. Here you find an overview of the major Bayer products.</span></h1>
    - ID: "6ddea92c-447e-45ba-810a-b0c67785cc52"
      Hint: Title
      Value: Products
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5f4fcf09-fe5c-4d0e-bc11-b09ae24e2040"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250424T043622Z
- Language: "en-GB"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}"
              p:before="*"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7BE25B16F8-81E2-443F-B4B0-500E08F42815%7D&amp;FieldNames=%7B5B290361-359A-440F-B069-A6B572F050C8%7D&amp;Styles=%7C%7BED9F23D9-7CB6-46AB-8AED-1086E2E517F2%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{ECBD8335-1F9E-4FCC-80CE-0E4B85E2A298}"
              p:after="r[@uid='{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}']"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Text%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=p8-7UeJ8C0&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=fM94UIWfrYAUphV&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Text%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
              s:ph="headless-main" />
            <r
              uid="{93306911-25A3-4414-A134-C6DFF667C3D1}"
              p:after="*[1=2]"
              s:ds="50647fa5-c746-4fb6-ac01-e4016fa0d017"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Image%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=cqLZMpmZph&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=xz4P-c_gGUeJ3Iu&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Image%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T090143Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rachit.bansal@valtech.com
    - ID: "6526ebe8-cb6e-4196-9f02-4406a7b939e8"
      Hint: Content
      Value: |
        <h1><span style="color: rgb(16, 56, 79);">With our products we contribute to the health of people, animals and plants. Here you find an overview of the major Bayer products.</span></h1>
    - ID: "6ddea92c-447e-45ba-810a-b0c67785cc52"
      Hint: Title
      Value: Products
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d18bb23f-a509-4bee-af39-59bf0a4ae04f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250424T055551Z
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}"
              p:before="*"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7BE25B16F8-81E2-443F-B4B0-500E08F42815%7D&amp;FieldNames=%7B5B290361-359A-440F-B069-A6B572F050C8%7D&amp;Styles=%7C%7BED9F23D9-7CB6-46AB-8AED-1086E2E517F2%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{ECBD8335-1F9E-4FCC-80CE-0E4B85E2A298}"
              p:after="r[@uid='{CDF76F20-A46D-485A-9A5C-7FA12B36F91D}']"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Text%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=p8-7UeJ8C0&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=fM94UIWfrYAUphV&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Text%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
              s:ph="headless-main" />
            <r
              uid="{93306911-25A3-4414-A134-C6DFF667C3D1}"
              p:after="*[1=2]"
              s:ds="50647fa5-c746-4fb6-ac01-e4016fa0d017"
              s:id="{CAA0C742-F052-49FB-825B-A03494798DB7}"
              s:par="ComponentName=Image%20Paragraph%20Component&amp;ComponentConfiguration&amp;LibraryId=3NhaQ9FxuHi25CM3mBQyjL&amp;ComponentId=cqLZMpmZph&amp;ComponentVersion=responsive&amp;ComponentRevision=staged&amp;ComponentHostName=https%3A%2F%2Ffeaas.blob.core.windows.net&amp;ComponentInstanceId=xz4P-c_gGUeJ3Iu&amp;ComponentDataOverride&amp;ComponentHTMLOverride&amp;ComponentLabel=Image%20Paragraph%20Component&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T090143Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rachit.bansal@valtech.com
    - ID: "6526ebe8-cb6e-4196-9f02-4406a7b939e8"
      Hint: Content
      Value: |
        <h1><span style="color: rgb(16, 56, 79);">With our products we contribute to the health of people, animals and plants. Here you find an overview of the major Bayer products.</span></h1>
    - ID: "6ddea92c-447e-45ba-810a-b0c67785cc52"
      Hint: Title
      Value: Products
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "28b93d6f-6365-4ba7-b7af-e1947b24248d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250425T050649Z
