---
ID: "788baeea-f7d0-4c72-8f86-5642e327d95c"
Parent: "00d31fc1-485a-44b7-acf5-a0d0f463e254"
Template: "dad2114f-837d-453b-94b4-b0bab83b1fc5"
Path: "/sitecore/content/collection-1/sample-site/Home/Services"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{1DB4F296-FDF2-4E32-A3A1-0672BB8BF537}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "77447490-ad4f-4aa3-b1d0-0bee12f9aefe"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{63682277-0F50-47B0-B1E8-53A775BFFFBD}"
              p:before="*"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B73A803CA-1370-4149-B498-D075E49BE5DA%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="/headless-main/sxa-servicemaincontent/container-3" />
            <r
              uid="{E9F90E23-2CF3-4485-9B07-2F01F5F9AD85}"
              p:after="*[1=2]"
              s:ds="local:/Data/Text 1"
              s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B7E198923-6E00-4931-8845-11A5162AE1FA%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/sxa-servicemaincontent/container-2" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T130224Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "6ddea92c-447e-45ba-810a-b0c67785cc52"
      Hint: Title
      Value: Explore Our Wide Range of Exceptional Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "20fe1750-a9cc-4d6a-a6e1-a5dd0421f06e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250424T043622Z
- Language: "en-GB"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{63682277-0F50-47B0-B1E8-53A775BFFFBD}"
              p:before="*"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B73A803CA-1370-4149-B498-D075E49BE5DA%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="/headless-main/sxa-servicemaincontent/container-3" />
            <r
              uid="{E9F90E23-2CF3-4485-9B07-2F01F5F9AD85}"
              p:after="*[1=2]"
              s:ds="local:/Data/Text 1"
              s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B7E198923-6E00-4931-8845-11A5162AE1FA%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/sxa-servicemaincontent/container-2" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T130224Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "6ddea92c-447e-45ba-810a-b0c67785cc52"
      Hint: Title
      Value: Explore Our Wide Range of Exceptional Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "940a75a3-e47d-4381-9246-fe5e0b503c1a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250424T055548Z
