name: Build Design Tokens on Change

on:
  push:
    paths:
      - 'headapps/nextjs-starter/src/token/**'
      - 'headapps/nextjs-starter/src/token/figma-tokens.json'

jobs:
  build_tokens:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: 📦 Install Dependencies
        run: npm ci
        working-directory: headapps/nextjs-starter

      - name: 🎨 Build Tokens
        run: npm run build:tokens
        working-directory: headapps/nextjs-starter

      - name: 📂 Commit Changes
        run: |
          BRANCH_NAME=token-update-$(date +%s)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add .
          git diff --cached --quiet || git commit -m "chore: update design tokens"
        working-directory: headapps/nextjs-starter

      - name: 🚀 Push Changes
        run: git push origin ${{ env.BRANCH_NAME }}
        working-directory: headapps/nextjs-starter

      - name: 📬 Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update design tokens
          branch: ${{ env.BRANCH_NAME }}
          title: 'Update design tokens'
          body: 'This PR includes updates to design tokens triggered by recent changes.'
          base: design-system-poc
