---
ID: "f1c10bdb-c489-4864-a8fc-45589f124534"
Parent: "3721dd5f-5ff2-46cf-a56b-8a1215243bae"
Template: "3721dd5f-5ff2-46cf-a56b-8a1215243bae"
Path: "/sitecore/templates/Project/collection-1/Services/Rendering Parameters/ServicePageContainer Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "27a7cd74-fb46-49b2-af7a-22ef26eb3bef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nagaraju.chatta@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250424T045016Z
